export default function form(props) {
  return [
    {
      id: "name",
      label: "Nome completo",
      placeholder: "Digite seu nome completo",
      mask: "alphabet",
      type: "TextInput",
      size: "big",
      action: "addToCart",
    },
    {
      id: "email",
      label: "E-mail",
      placeholder: "Digite seu e-mail",
      type: "TextInput",
      size: "big",
      action: "addToCart",
    },
    {
      id: "phone",
      label: "Telefone",
      placeholder: "(00) x0000-0000",
      mask: "phone",
      type: "TextInput",
      size: "small",
      action: "addToCart",
    },
    {
      id: "zipCode",
      label: "CEP",
      placeholder: "Digite seu CEP",
      mask: "zipCode",
      type: "TextInput",
      size: "small",
      action: "fillAddress",
      blur: props.getAddressData,
    },
    {
      id: "address",
      label: "Endereço",
      placeholder: "Digite seu endereço",
      type: "TextInput",
      size: "big",
      disabled: props.isFieldDisabled("address"),
    },
    {
      id: "addressNumber",
      label: "Número",
      placeholder: "Número",
      mask: "number",
      type: "TextInput",
      size: "small",
      action: "fillAddress",
      showCheckbox: true,
      checkboxLabel: "Sem número",
      checkboxChange: props.checkboxChange,
      disabled: props.numberDisabled,
    },
    {
      id: "addressComplement",
      label: "Complemento",
      placeholder: "Digite seu complemento",
      type: "TextInput",
      size: "small",
    },
    {
      id: "district",
      label: "Bairro",
      placeholder: "Digite seu bairro",
      type: "TextInput",
      size: "big",
      disabled: props.isFieldDisabled("district"),
    },
    {
      id: "city",
      label: "Cidade",
      placeholder: "Digite sua cidade",
      type: "TextInput",
      mask: "alphabet",
      size: "small",
      disabled: props.isFieldDisabled("city"),
    },
    {
      id: "state",
      label: "Estado",
      placeholder: "Selecione seu estado",
      type: "SelectInput",
      size: "small",
      disabled: props.isFieldDisabled("state"),
      options: props.states,
    },
  ];
}
